### ISSUE TITLE
No handling for empty lists

### ISSUE THREAD

**Issue by PetrGlad** [Zubnix/udev-java-bindings#1]
Functions returning ListEntry may return null. Presumably in case of empty lists.
But the library always returns LIstEntry instance. E.g. as in  

```
UdevLibrary.INSTANCE().udev_device_get_devlinks_list_entry(getPointer())
```

In this case there is no clear indication that list is empty and ListEntry.hashCode would fail with NullPointerException because `ListEntry.pointer` field is null.

**Comment by Zubnix** [comment]
I see. This actually an easy fix `pointer == null?return null: return new Foo(pointer);` . If you know by accident any other functions that have this, you may include them in the bug report so I can fix those as well.

**Comment by PetrGlad** [comment]
It looks like all calls of `*_list_entry` are affected (in classes `Devices`, `Enumerate`, `HardwareDB`).

**Comment by Zubnix** [comment]
fix pushed 7627c678e can you review?

**Comment by Zubnix** [comment]
have a lookt at 6c304f26

**Comment by PetrGlad** [comment]
6c304f2 looks good.

(As a side issue similar `create` method in Device class would streamline code also.)
